# Generated by Django 2.2.5 on 2019-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
