# Generated by Django 2.2.5 on 2019-09-24 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20190924_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_member',
            new_name='ProjectMember',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description? You can add one!'),
        ),
    ]
