# Generated by Django 2.2.5 on 2019-09-24 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20190924_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_comment',
            new_name='TaskComment',
        ),
        migrations.RenameModel(
            old_name='Task_document',
            new_name='TaskDocument',
        ),
    ]
