# Generated by Django 2.2.5 on 2019-09-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.IntegerField(choices=[(1, 'To do'), (2, 'In progress'), (3, 'Clone'), (4, 'New')], default=4),
        ),
    ]
