# Generated by Django 2.2.2 on 2019-07-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='folder',
        ),
    ]
