# Generated by Django 2.2.2 on 2019-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_folder_tilt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
