# Generated by Django 2.2.2 on 2019-07-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190724_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder2',
            new_name='Folder',
        ),
    ]
