# Generated by Django 2.2.2 on 2019-07-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190715_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Label'),
        ),
    ]
