# Generated by Django 2.2.2 on 2019-07-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_category_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.Folder'),
            preserve_default=False,
        ),
    ]
