STATUS_TODO = 1
STATUS_IN_PROGRESS = 2
STATUS_DONE = 3
STATUS_NEW = 4

STATUS_CHOICES = (
    (STATUS_TODO, "To do"),
    (STATUS_IN_PROGRESS, "In progress"),
    (STATUS_DONE, "Done"),
    (STATUS_NEW, "New")
)
